author = "sharkdp"
description = "A simple, fast and user-friendly alternative to 'find'"
homepage = "https://github.com/sharkdp/fd"
license = "MIT"
binaries = [
    "bin/fd",
]
name = "fd"
deps = []
chmod = []
